import os
import json
import discord
from discord.ext import commands
import time
import asyncio
import sys

def change_title(title: str): #Credits: Doci Team
    if os.name in ["nt", "dos"]: #Check OS Name
        try: os.system("title "+title)
        except: pass
    return

def clear_console(): #Credits: Doci Team
    if os.name in ["nt", "dos"]: #Check OS Name
        try: os.system("cls")
        except: pass
    else:
        try: os.system("clear")
        except: pass
    return

class color: #Credits: Doci Team
    Red = "\033[91m"
    Green = "\033[92m"
    Blue = "\033[94m"
    Cyan = "\033[96m"
    White = "\033[97m"
    Yellow = "\033[93m"
    Magenta = "\033[95m"
    Grey = "\033[90m"
    Black = "\033[90m"
    Default = "\033[99m"

change_title("Test Discord Bot PY")
clear_console()

if os.path.exists("Config.json"):
  try: Config = json.load(open("Config.json"))
  except Exception as error:
    json.dump({ "Server ID": 0, "Channel ID": 0 }, open("Config.json", "w"))
    sys.exit("Invalid Config! Error:\n"+str(error))
else:
  json.dump({ "Server ID": 0, "Channel ID": 0 }, open("Config.json", "w"))
  sys.exit("No Config File, Config Now!")
if not "Server ID" in Config or not "Channel ID" in Config:
  json.dump({ "Server ID": 0, "Channel ID": 0 }, open("Config.json", "w"))
  sys.exit("Required Configs Not Found, Config Again!")

client = commands.Bot(command_prefix="!", help_command=None, case_insensitive=True, self_bot=True)
@client.event
async def on_message(message): #New
  global Config
  if not message.channel.type == discord.ChannelType.private and not message.channel.type == discord.ChannelType.group and message.guild.id == Config["Server ID"] and message.channel.id == Config["Channel ID"]:
    if message.content == "You don't have a fishing pole, you need to go buy one. You're not good enough to catch them with your hands.":
      await message.channel.send("pls withdraw all")
      await message.channel.send("pls buy fishingpole")
    if message.content == "You don't have a shovel, you need to go buy one. I'd hate to let you dig with your bare hands.":
      await message.channel.send("pls withdraw all")
      await message.channel.send("pls buy shovel")
    if message.content == "You don't have a hunting rifle, you need to go buy one. You're not good enough to shoot animals with your bare hands... I hope.":
      await message.channel.send("pls withdraw all")
      await message.channel.send("pls buy rifle")
    if message.content == "You went to shoot the dragon, but you have terrible aim. Missing the shot, the dragon ate you. LOL":
      await message.channel.send("pls withdraw all")
      await message.channel.send("pls buy lifesaver")
    await client.process_commands(message)

@client.event
async def on_ready():
  await client.change_presence(status=discord.Status.offline)
  print(color.Green+f"{client.user} is online!")
  global Config
  await client.get_channel(Config["Channel ID"]).send("!AutoDank") #New
  import os #New
  from datetime import datetime #New
  while True: #New
    if not os.path.exists("Last Daily") or datetime.now().strftime("%d %m %Y") != open("Last Daily").read():
      await client.get_channel(Config["Channel ID"]).send("pls daily")
      open("Last Daily", "w").write(datetime.now().strftime("%d %m %Y"))
    if os.path.exists("Last Monthly"):
      try:
        LastMonthly = float(open("Last Monthly").read())
        LastMonthly_ok = True
      except: LastMonthly_ok = False
    else: LastMonthly_ok = False
    if not LastMonthly_ok or LastMonthly < time.time():
      await client.get_channel(Config["Channel ID"]).send("pls monthly")
      open("Last Monthly", "w").write(str(time.time()+2592000))
    await asyncio.sleep(120)

@client.command()
async def helpdank(ctx):
  await ctx.message.delete()
  await ctx.send("```!$AutoDank: Pls beg, Pls dig, Pls fish, pls hunt, dep all. \n!StopAutoDank: Stops the bot. This code can bypass ban```")

@client.command()
async def help(ctx):
  await ctx.message.delete()
  await ctx.send("```!AutoDank: Pls beg, Pls dig, Pls fish, pls hunt, dep all. \n!StopAutoDank: Stops the bot. This code can bypass ban```")

@client.command()
async def stopautodank(ctx):
  await ctx.message.delete()
  await ctx.send("**AutoDank is now Disabled 😊**")
  global dmcs
  dmcs = False


@client.command()#pass_context=True)
async def autodank(ctx):
  try:
    await ctx.message.delete()
    await ctx.send("**AutoDank is now Enabled 😊**")
    global dmcs
    dmcs = True
    while dmcs:
      async with ctx.typing():
        await asyncio.sleep(5)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(120)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(120)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(120)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(45)
        await ctx.send("pls fish")
        await asyncio.sleep(1)
        await ctx.send("pls dig")
        await asyncio.sleep(1)
        await ctx.send("pls hunt")
        await ctx.send("pls beg")
        await asyncio.sleep(1)
        await ctx.send("pls dep all")
        await asyncio.sleep(120)
  except:
    os.system("kill 1")
    sys.exit(6)

from flask import Flask
from threading import Thread
from waitress import serve

app = Flask("")

@app.route("/")
def home(): return "I'm alive"
def run(): serve(app, host="0.0.0.0", port=80)#app.run(host="0.0.0.0", port=8080)
Thread(target=run).start()

try: client.run(os.environ["Token"], bot=False)
except:
  os.system("kill 1")
  sys.exit(6)
sys.exit(2)
